name = "feeddeck"
compatibility_date = "2024-01-01"
pages_build_output_dir = "src"

# 定时任务（每5分钟）
[triggers]
crons = ["*/5 * * * *"]

# D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "feeddeck-db"
database_id = "69438eef-2e4b-49b3-803d-8bf853ed9163"

# KV 命名空间
[[kv_namespaces]]
binding = "KV"
id = "e88e12c264f14cc5818de69487a125fe"
